/*
 * Copyright (c) 2020 V2C Development Team. All rights reserved.
 * Licensed under the Version 0.0.1 of the V2C License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at <https://tinyurl.com/v2c-license>.
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions 
 * limitations under the License.
 */
package edu.uco.cs.v2c.dispatcher.net.websocket.outgoing;

import java.util.UUID;

import org.json.JSONObject;

import edu.uco.cs.v2c.dispatcher.net.websocket.MalformedPayloadException;
import edu.uco.cs.v2c.dispatcher.net.websocket.outgoing.OutgoingPayload.OutgoingAction;

/**
 * Encapsulates the outgoing {@link OutgoingAction#HEARTBEAT} payload.
 * 
 * @author Caleb L. Power
 */
public class HeartbeatPayload extends OutgoingPayload {
  
  private static final String KEY_VAR = "key";
  private static final String TIMESTAMP_VAR = "timestamp";
  
  private long timestamp = -1L;
  private UUID key = null;
  
  /**
   * Overloaded constructor to instantiate the payload.
   */
  public HeartbeatPayload() {
    super(OutgoingAction.HEARTBEAT);
  }
  
  /**
   * Retrieves the unique key of this particular wellness check.
   * 
   * @return the theoretically unique key
   */
  public UUID getKey() {
    return key;
  }
  
  /**
   * Sets the unique key of this particular wellness check.
   * 
   * @param key the unique key
   * @return this payload
   */
  public HeartbeatPayload setKey(UUID key) {
    this.key = key;
    return this;
  }
  
  /**
   * Retrieves the timestamp representing the time at which this payload was
   * generated by this server prior to dispatch.
   * 
   * @return the number of milliseconds after the UNIX epoch during which this
   *         wellness check was generated
   */
  public long getTimestamp() {
    return timestamp;
  }
  
  /**
   * Sets the timestamp that should represent the time at which this payload
   * was generated prior to dispatch.
   * 
   * @param timestamp the number of milliseconds after the UNIX epoch during
   *        which this payload was generated
   * @return this payload
   */
  public HeartbeatPayload setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    return this;
  }
  
  /**
   * {@inheritDoc}
   */
  @Override public JSONObject serialize() throws MalformedPayloadException {
    if(timestamp < 0 || key == null)
      throw new MalformedPayloadException(action, "Invalid payload.");
    
    return new JSONObject()
        .put(ACTION_VAR, action)
        .put(KEY_VAR, key.toString())
        .put(TIMESTAMP_VAR, timestamp);
  }
  
}
